<a href="https://colab.research.google.com/github/maskubica/ml-concepts/blob/main/Linear_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import fetch_california_housing
import pandas as pd
import matplotlib.pyplot as plt
from torch.optim import SGD
import torch
import numpy as np

%matplotlib inline


In [2]:
X, y = fetch_california_housing(as_frame=True, return_X_y = True)
X.shape

(20640, 8)

In [3]:
X.head()

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0  8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1  8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2  7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3  5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4  3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   

   Longitude  
0    -122.23  
1    -122.22  
2    -122.24  
3    -122.25  
4    -122.25

In [166]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()
model.fit(X, y)

y_hat = model.predict(X)


In [27]:
X_tensor = torch.tensor(X.values)
y_tensor = torch.tensor(y.values)
y_tensor = torch.unsqueeze(y_tensor, dim=1)




X_tensor.mm(theta)
y_tensor.shape

theta

Parameter containing:
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]], dtype=torch.float64, requires_grad=True)

In [86]:
def loss_fn(output, target):
  return torch.sqrt(torch.mean((output - target)**2))


output = X_tensor.mm(theta)
loss_fn(output, y_tensor)

tensor(2.3686, dtype=torch.float64, grad_fn=<SqrtBackward0>)

In [145]:
theta = torch.randn(8,1, dtype=torch.float64)
theta = torch.nn.parameter.Parameter(theta)

optimizer = SGD([theta], lr=0.000001, momentum=0.9)

In [171]:
for i in range(0,50000):
  optimizer.zero_grad()
  output = X_tensor.mm(theta)
  loss = loss_fn(output, y_tensor)
  print(loss)
  loss.backward()
  optimizer.step()

Strumieniowane dane wyjściowe obcięte do 5000 ostatnich wierszy.
tensor(0.8748, dtype=torch.float64, grad_fn=<SqrtBackward0>)
tensor(0.8748, dtype=torch.float64, grad_fn=<SqrtBackward0>)
tensor(0.8748, dtype=torch.float64, grad_fn=<SqrtBackward0>)
tensor(0.8748, dtype=torch.float64, grad_fn=<SqrtBackward0>)
tensor(0.8748, dtype=torch.float64, grad_fn=<SqrtBackward0>)
tensor(0.8748, dtype=torch.float64, grad_fn=<SqrtBackward0>)
tensor(0.8748, dtype=torch.float64, grad_fn=<SqrtBackward0>)
tensor(0.8748, dtype=torch.float64, grad_fn=<SqrtBackward0>)
tensor(0.8748, dtype=torch.float64, grad_fn=<SqrtBackward0>)
tensor(0.8748, dtype=torch.float64, grad_fn=<SqrtBackward0>)
tensor(0.8748, dtype=torch.float64, grad_fn=<SqrtBackward0>)
tensor(0.8748, dtype=torch.float64, grad_fn=<SqrtBackward0>)
tensor(0.8748, dtype=torch.float64, grad_fn=<SqrtBackward0>)
tensor(0.8748, dtype=torch.float64, grad_fn=<SqrtBackward0>)
tensor(0.8748, dtype=torch.float64, grad_fn=<SqrtBackward0>)
tensor(0.8748, dtype

In [172]:
theta.data.round(decimals=1)

tensor([[0.4000],
        [0.0000],
        [0.0000],
        [-0.0000],
        [-0.0000],
        [-0.0000],
        [-0.0000],
        [-0.0000]], dtype=torch.float64)

In [173]:
np.round(model.coef_,4)

array([ 0.4367,  0.0094, -0.1073,  0.6451, -0.    , -0.0038, -0.4213,
       -0.4345])

array([4.13164983, 3.97660644, 3.67657094, ..., 0.17125141, 0.31910524,
       0.51580363])

In [174]:
 np.mean((y - y_hat)**2)
 

0.5243209861846078

In [138]:
loss_fn(model.coef_.dot(X.T), y)

TypeError: ignored

In [ ]:
optimizer = SGD(model.parameters(), lr=0.01, momentum=0.9)

In [ ]:
for input, target in dataset:
    def closure():
        optimizer.zero_grad()
        output = model(input)
        loss = loss_fn(output, target)
        loss.backward()
        return loss
    optimizer.step(closure)